---
#-----------------------------------------------------------------
# MYSQL_IDENTITY
#-----------------------------------------------------------------
# mysql_cluster:       #CLUSTER  # required cluster name
# mysql_seq: 1         #INSTANCE # {1} for standalone, {1,2,3} for MGR

#-----------------------------------------------------------------
# MYSQL_BUSINESS
#-----------------------------------------------------------------
mysql_root_password: DBUser.Root
mysql_monitor_password: DBUser.Monitor
mysql_cluster_password: DBUser.Cluster
mysql_databases: []              # [{ name, encoding, collate, encrypt }]
mysql_users: []                  # [{ name, host, password, connlimit, priv }]
mysql_parameters: {}             # extra [mysqld] options, e.g. { max_connections: 500 }

#-----------------------------------------------------------------
# MYSQL_BACKUP
#-----------------------------------------------------------------
mysql_backup_enabled: true
mysql_backup_repo:
  local: { path: /data/backups/mysql, retention: 7 }

#-----------------------------------------------------------------
# MYSQL_MONITOR
#-----------------------------------------------------------------
mysql_exporter_enabled: true
...
