---
#-----------------------------------------------------------------
# KAFKA_REMOVE
#-----------------------------------------------------------------
kafka_safeguard: false            # prevent purging a running kafka cluster?
kafka_rm_data: true               # remove kafka data dir & /etc/kafka recovery state?
kafka_rm_pkg: false               # uninstall kafka & kafka-exporter packages?

#-----------------------------------------------------------------
# KAFKA (REFERENCE)
#-----------------------------------------------------------------
kafka_data: /data/kafka           # kafka data directory (must match the kafka role)
...
