---
#-----------------------------------------------------------------
# MYSQL_REMOVE
#-----------------------------------------------------------------
mysql_safeguard: true                    # abort mysql_remove unless explicitly false
mysql_rm_confirm: ''                     # exact mysql instance or cluster name
...
