---
galaxy_info:
  role_name: mysql
  description: deploy MySQL 8.4 LTS standalone or native single-primary InnoDB Cluster
  min_ansible_version: '2.9'
  author: 'Ruohang Feng / @Vonng / rh@vonng.com'
  license: Apache-2.0
  platforms:
    - name: EL
      versions: [all]
    - name: Ubuntu
      versions: [all]
    - name: Debian
      versions: [all]
  galaxy_tags:
    - pigsty
    - mysql
    - database
    - victoriametrics
dependencies: []
...
