# check .env files before running
services:
  minio:
    container_name: minio
    image: pgsty/minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: S3User.MinIO
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /data/minio:/data
    command: |
      server /data --console-address ":9001"
