---
#--------------------------------------------------------------#
# HONOR PG_SAFEGUARD                              [pg_safeguard]
#--------------------------------------------------------------#
- name: ABORT due to pg_safeguard enabled
  connection: local
  when: pg_safeguard|bool
  tags: [ always ,pg_safeguard ]
  any_errors_fatal: true
  ignore_errors: false
  fail: msg="Abort due to pg_safeguard for {{ pg_cluster }}-{{ pg_seq }} @ {{ inventory_hostname }} is enabled, override with -e pg_safeguard=false"

#--------------------------------------------------------------#
# remove targets from victoria          [rm_metrics][pg_monitor]
#--------------------------------------------------------------#
- import_tasks: victoria.yml
  tags: [ pg_monitor, pg_deregister, deregister, rm_metrics ]

#--------------------------------------------------------------#
# remove pgsql datasource from grafana       [rm_ds][pg_monitor]
#--------------------------------------------------------------#
# the database 'postgres' is registered by default
# if postgres is explicitly defined, it will be overridden
- include_tasks: grafana.yml
  tags: [ pg_monitor, pg_deregister, deregister, rm_ds ]
  when: grafana_enabled|bool
  vars: { database: "{{ item }}" }
  with_items: "{{ [{'name': 'postgres'}] + pg_databases|default([]) }}"

#--------------------------------------------------------------#
# remove postgres monitor              [pg_monitor][pg_exporter]
#--------------------------------------------------------------#
- import_tasks: pg_exporter.yml
  tags: [ pg_monitor ,pg_exporter ]

#--------------------------------------------------------------#
# remove pgbouncer monitor      [pg_monitor][pgbouncer_exporter]
#--------------------------------------------------------------#
- import_tasks: pgbouncer_exporter.yml
  tags: [ pg_monitor, pgbouncer_exporter ]

#--------------------------------------------------------------#
# remove pgbackrest monitor    [pg_monitor][pgbackrest_exporter]
#--------------------------------------------------------------#
- import_tasks: pgbackrest_exporter.yml
  tags: [ pg_monitor, pgbackrest_exporter ]

#--------------------------------------------------------------#
# remove pg dns records                         [pg_access][dns]
#--------------------------------------------------------------#
- import_tasks: dns.yml
  tags: [ pg_access, dns , rm_dns ]

#--------------------------------------------------------------#
# remove pg vip manager                         [pg_access][vip]
#--------------------------------------------------------------#
- import_tasks: vip.yml
  tags: [ pg_access, vip ]

#--------------------------------------------------------------#
# remove service                         [pg_access][pg_service]
#--------------------------------------------------------------#
- import_tasks: pg_service.yml
  tags: [ pg_access, pg_service, haproxy ]

#--------------------------------------------------------------#
# remove pgbouncer                        [pg_access][pgbouncer]
#--------------------------------------------------------------#
- import_tasks: pgbouncer.yml
  tags: [ pg_access, pgbouncer ]

#--------------------------------------------------------------#
# remove crontab                                    [pg_crontab]
#--------------------------------------------------------------#
- name: remove postgres dbsu crontab
  tags: [ pg_crontab ]
  ignore_errors: true
  file:
    path: "{% if os_package == 'deb' %}/var/spool/cron/crontabs/{% else %}/var/spool/cron/{% endif %}{{ pg_dbsu }}"
    state: absent

#--------------------------------------------------------------#
# remove postgres                       [pg_bootstrap][postgres]
#--------------------------------------------------------------#
# pg_replica, pg_primary, pg_meta
- import_tasks: postgres.yml
  tags: [ pg_bootstrap, postgres, patroni ]

#--------------------------------------------------------------#
# remove backup                                      [pg_backup]
#--------------------------------------------------------------#
- import_tasks: pgbackrest.yml
  tags: [ pg_backup, pgbackrest ]
  when: pg_rm_backup|bool

#--------------------------------------------------------------#
# remove data                                          [pg_data]
#--------------------------------------------------------------#
- name: remove postgres data
  tags: pg_data
  when: pg_rm_data|bool
  ignore_errors: true
  file: path={{ item }} state=absent
  with_items:
    - /pg/data
    - "{{ pg_fs_main }}/postgres"

#--------------------------------------------------------------#
# uninstall packages (and extensions)                   [pg_pkg]
#--------------------------------------------------------------#
# tag: pg_ext for remove extensions only
- import_tasks: uninstall.yml
  tags: pg_pkg
  when: pg_rm_pkg|bool

#--------------------------------------------------------------#
# remove vector logs                       [rm_logs][pg_monitor]
#--------------------------------------------------------------#
- name: remove pgsql logs from vector
  tags: [ pg_monitor, pg_deregister, deregister, rm_logs ]
  when: vector_enabled|default(true)|bool
  ignore_errors: true
  block:
    - name: remove pgsql vector logging config
      file: path=/etc/vector/{{ item }}.yaml state=absent
      with_items: [ postgres, patroni, pgbackrest ]
    - name: reload vector to discard pgsql log
      systemd: name=vector state=reloaded enabled=yes daemon_reload=yes

...
