#!/bin/bash
set -euo pipefail
#==============================================================#
# File      :   supa-kick
# Desc      :   used by supabase, use dummy update to kick lag
# Ctime     :   2025-05-08
# Mtime     :   2026-04-10
# Path      :   /pg/bin/supa-kick
# Deps      :   psql
# Docs      :   https://github.com/pgsty/pigsty/issues/581
# License   :   Apache-2.0 @ https://pigsty.io/docs/about/license/
# Copyright :   2018-2026  Ruohang Feng / Vonng (rh@vonng.com)
#==============================================================#

# perform regular dummy update on the internal _supabase._analytics table to kick lag feedback
db="${SUPABASE_INTERNAL_DB:-_supabase}"
if psql "${db}" -Atqc "select to_regclass('_analytics.users') is not null" 2>/dev/null | grep -qx t; then
  psql "${db}" -Atqwc 'update _analytics.users SET id = 1 where id = 1;'
fi
